"""Generate a Markdown competitor GEO intelligence report with trend data."""
from __future__ import annotations
from datetime import date
from visibility_scorer import VisibilityReport
from history_store import HistoryStore
from logger import get_logger

log = get_logger("report_writer")


class ReportWriter:
    def __init__(self, store: HistoryStore):
        self._store = store

    def write(self, report: VisibilityReport, my_brand: str) -> str:
        lines: list[str] = [
            f"# Competitor GEO Intelligence Report",
            f"**Date:** {date.today()}  |  **Category:** {report.category}  |  **Probes:** {report.probe_count}",
            "",
            "## Visibility Rankings",
            "",
            "| Rank | Brand | Visibility | Mentions | Models |",
            "|------|-------|-----------|----------|--------|",
        ]

        for i, b in enumerate(report.brands, 1):
            marker = " ⭐" if b.brand == my_brand else ""
            lines.append(
                f"| {i} | **{b.brand}**{marker} | {b.visibility_pct}% | "
                f"{b.mention_count}/{b.total_probes} | {', '.join(b.models_mentioned) or '—'} |"
            )

        lines += ["", "## Trend Analysis (last 8 weeks)", ""]

        for b in report.brands:
            trend = self._store.get_trend(b.brand, report.category, weeks=8)
            if len(trend) < 2:
                continue
            latest = trend[0]["visibility_pct"]
            previous = trend[1]["visibility_pct"]
            delta = latest - previous
            arrow = "↑" if delta > 0 else ("↓" if delta < 0 else "→")
            lines.append(f"- **{b.brand}**: {latest}% {arrow} ({delta:+.1f}% vs last week)")

        lines += [
            "",
            "## Strategic Insights",
            "",
        ]

        # Find own brand rank
        brand_names = [b.brand for b in report.brands]
        own_rank = brand_names.index(my_brand) + 1 if my_brand in brand_names else None
        if own_rank:
            above = [b.brand for b in report.brands[:own_rank - 1]]
            lines.append(f"- **{my_brand}** ranks #{own_rank} of {len(report.brands)} tracked brands.")
            if above:
                lines.append(f"- Outranked by: {', '.join(above)}")
        else:
            lines.append(f"- **{my_brand}** was not mentioned in any LLM response this week.")

        top = report.brands[0] if report.brands else None
        if top and top.brand != my_brand:
            gap = top.visibility_pct - (report.brands[brand_names.index(my_brand)].visibility_pct
                                        if my_brand in brand_names else 0)
            lines.append(f"- Gap to leader **{top.brand}**: {gap:.1f} percentage points.")

        lines += [
            "",
            "---",
            f"*Generated by Competitor GEO Intelligence Tracker · Saikou.tech*",
        ]

        return "\n".join(lines)
